### ISSUE TITLE
Tests fail with "Cannot read property 'child' of undefined"

### ISSUE THREAD

**Issue by bedrich-schindler** [wojtekmaj/enzyme-adapter-react-17#25] opened 2021-08-16 07:55 UTC
Hi,

I know that this adapter is temporary and the only way to use enzyme with React 17 and I am not sure how much time do you invest in its maintenance, but if you do, I met error which I was trying to solve in past year without success. I ran into it again after few months so I decided to create this issue.

I have been updating our [open-source React UI library](https://github.com/react-ui-org/react-ui) (_still in development_) and as part of maintenance task I have been trying to update React 16 to React 17 and use your adapter for React 17. But if I do this, some tests fail with error:

```
Cannot read property 'child' of undefined
TypeError: Cannot read property 'child' of undefined
    at getFiber (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/@wojtekmaj/enzyme-adapter-react-17/src/detectFiberTags.js:15:31)
    at detectFiberTags (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/@wojtekmaj/enzyme-adapter-react-17/src/detectFiberTags.js:75:15)
    at ReactSeventeenAdapter.createMountRenderer (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/@wojtekmaj/enzyme-adapter-react-17/src/ReactSeventeenAdapter.js:421:19)
    at ReactSeventeenAdapter.createRenderer (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/@wojtekmaj/enzyme-adapter-react-17/src/ReactSeventeenAdapter.js:792:51)
    at new ReactWrapper (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/enzyme/src/ReactWrapper.js:113:32)
    at mount (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/enzyme/src/mount.js:10:10)
    at Object.<anonymous> (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/src/lib/components/ui/Alert/__tests__/Alert.test.jsx:10:18)
    at Promise.then.completed (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/jest-circus/build/utils.js:390:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/jest-circus/build/utils.js:315:10)
    at _callCircusTest (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/jest-circus/build/run.js:60:9)
    at run (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:166:21)
    at jestAdapter (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/jest-runner/build/runTest.js:481:34)
    at TestRunner.runTests (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/jest-runner/build/index.js:111:12)
    at TestScheduler.scheduleTests (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/@jest/core/build/TestScheduler.js:333:13)
    at runJest (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/@jest/core/build/runJest.js:387:19)
    at _run10000 (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/@jest/core/build/cli/index.js:408:7)
    at runCLI (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/@jest/core/build/cli/index.js:261:3)
    at Object.run (/Users/bedrich.schindler/VisionApps/Projekty/va/react-ui/node_modules/jest/node_modules/jest-cli/build/cli/index.js:163:37)
```

Weird thing is that only some of tests fail with this error.

Enzyme configuration tests/setupEnzyme.js (different from git version as I have those changes on local machine only):

```js
import Enzyme from 'enzyme';
import Adapter from '@wojtekmaj/enzyme-adapter-react-17';
import { createSerializer } from 'enzyme-to-json';

// Configure enzyme to use adapter for React
Enzyme.configure({ adapter: new Adapter() });

// Configure jest to use json serializer for snapshot creation
expect.addSnapshotSerializer(createSerializer({
  ignoreDefaultProps: true,
  mode: 'deep',
  noKey: true,
}));
```

Example test [src/lib/components/ui/Alert/__tests__/Alert.test.jsx](https://github.com/react-ui-org/react-ui/blob/master/src/lib/components/ui/Alert/__tests__/Alert.test.jsx):

```js

import React from 'react';
import sinon from 'sinon';
import { mount } from 'enzyme';
import { shallowToJson } from 'enzyme-to-json';
import defaultTranslations from '../../../../translations/en';
import { Alert } from '../Alert';

describe('rendering', () => {
  it('renders correctly', () => {
    const tree = mount(
      <Alert translations={defaultTranslations.Alert}>
        <div>Children</div>
      </Alert>,
    );

    expect(shallowToJson(tree)).toMatchSnapshot();
  });

  it('renders correctly with all props', () => {
    const tree = mount(
      <Alert
        closeHandler={() => {}}
        color="success"
        icon={<span className="icon" />}
        id="custom-id"
        translations={defaultTranslations.Alert}
      >
        <div>Children</div>
      </Alert>,
    );

    expect(shallowToJson(tree)).toMatchSnapshot();
  });
});
```

Example test [src/lib/components/ui/Alert/Alert.jsx](https://github.com/react-ui-org/react-ui/blob/master/src/lib/components/ui/Alert/Alert.jsx):

```js
import PropTypes from 'prop-types';
import React from 'react';
import getRootColorClassName from '../../../helpers/getRootColorClassName';
import { withProviderContext } from '../../../provider';
import styles from './Alert.scss';

export const Alert = ({
  children,
  closeHandler,
  color,
  icon,
  id,
  translations,
}) => (
  <div
    className={[
      styles.root,
      getRootColorClassName(color, styles),
    ].join(' ')}
    id={id}
    role="alert"
  >
    {icon && (
      <div className={styles.icon}>
        {icon}
      </div>
    )}
    <div
      className={styles.message}
      {...(id && { id: `${id}__content` })}
    >
      {children}
    </div>
    {closeHandler && (
      <button
        type="button"
        {...(id && { id: `${id}__close` })}
        className={styles.close}
        onClick={() => closeHandler()}
        onKeyPress={() => closeHandler()}
        tabIndex="0"
        title={translations.close}
      >
        <span className={styles.closeSign}>×</span>
      </button>
    )}
  </div>
);
```

As we use named export of Alert component instead of default export with React Context, there should not be any problem as there is almost anything to fail. But even if i replace content of the component with `<div />`, it fails with same error. But it happens only for tests using `mount`, `shallow` tests works fine.

**Comment by jdnichollsc** [comment] 2021-08-18 05:29
I'm getting the same error with React Native, please check my reproducible demo project here: https://github.com/proyecto26/MyApp

**Comment by peterphan1996** [comment] 2021-08-30 08:56
@jdnichollsc I have the same problem with React Native

**Comment by wojtekmaj** [comment] 2021-08-30 11:40
@jdnichollsc 

* `react-native-mock-render` you have installed depends on `react-dom` version 16.x, which conflicts with your React version, causing said error.
* You've installed `react-test-renderer` version 16.x, which also conflicts with your React version.
* You didn't follow https://github.com/enzymejs/enzyme/blob/master/docs/guides/react-native.md

@peterphan1996 Also see above.

**Comment by peterphan1996** [comment] 2021-08-30 14:24
Thanks @wojtekmaj I got it working

**Comment by jdnichollsc** [comment] 2021-08-30 14:26
> @bedrich-schindler got a branch I could look at?
> 
> @jdnichollsc 
> 
> * `react-native-mock-render` you have installed depends on `react-dom` version 16.x, which conflicts with your React version, causing said error.
> * You've installed `react-test-renderer` version 16.x, which also conflicts with your React version.
> * You didn't follow https://github.com/enzymejs/enzyme/blob/master/docs/guides/react-native.md
> 
> @peterphan1996 Also see above.

Thanks for your collaboration, let me check what's missing because I followed that configuration 🤔

**Comment by jdnichollsc** [comment] 2021-08-31 03:00
It's working perfect now, thank you! <3

**Comment by bedrich-schindler** [comment] 2021-09-06 10:57
@wojtekmaj I had been trying to solve it several times during past months but when I created reproducable for you with React 17.0.2 and your adapter 0.6.3, it has started to work. Our code did not change since that time and I have no clue what could it be. So it is resolved from my point of view, but others like @durgeshrkumari have observed same problems

**Comment by wojtekmaj** [comment] 2021-09-06 12:56
Most of the time it will be one of the causes I've mentioned above, so while this is not a support forum, I'll try and help resolving them case by case. As the OP has the issue resolved I'm going to close this thread.

**Closed by wojtekmaj** 2021-09-06 12:56 UTC
Labels: question

**Comment by GhayoorUlHaq** [comment] 2021-11-01 09:15
> It's working perfect now, thank you! <3

Can you show your configuration?
